### ISSUE TITLE
Bot Discord random create team

### ISSUE THREAD

**Issue by MartinBora** [Duck5el/discord-random-team-generating-bot#2]
hello. can you explain me how to create the argument vm. to be able to run the bot.
download the repository add the token to "application.java"
and I can't run the bot. also the "discordteambot" folder tells me that "java file outside of source root"

**Comment by Duck5el** [comment]
First of all can please visit the Discord Developer page and revoke the token of your bot because you just posted it in this Screenshot. Everyone who is reading this can abuse the bot and steal information from your server or harm you in other ways.

Second, if you are operating on Linux it is easier for you to install Docker and Docker-Compose and just use my example [docker-compose.yaml](https://github.com/Duck5el/discord-random-team-generating-bot/blob/main/docker-compose.yaml)
Also then you don't need to worry about the folder in the root directory.

But if you really want to run the bot in your IDE. You need to set up the vm-arguments you don't do that by replacing the sting in the source code.
Just follow this instruction on [stackoverflow](https://stackoverflow.com/a/50938399)

**Comment by Duck5el** [comment]
If you need any more help you can also msg me on Discord: Duck#4303
And I can run it through with you how to get the bot running.

**Comment by MartinBora** [comment]
thanks for your help. luckily i was able to use the bot with the vm argument.

**Comment by Duck5el** [comment]
That is great! I hope u also got around the problem with the matches folder in the root dir?
